[basic]
## required
host = "127.0.0.1"
## required
port = 4000
## required
user = "root"
## required
password = "root"

[flashback]
## required
db = ""
## required
table =""
## required，format example: "2020-01-01 00:00:00",should be later than tikv_gc_safe_point
until_time = "2020-01-01 00:00:00"
## batch size for a single thread，default 1000
batch_size = 1000
## concurrent running database connections, default 20
max_workers = 20
## true/false, overide original table or not after flashback
override = false

[dml]
## required
db = ""
## required
table = ""
## required, only one sql a time
sql = ""
## min _tidb_rowid when split sql, default min(_tidb_rowid)
# start_rowid =
## max _tidb_rowid when split sql, default max(_tidb_rowid)
# end_rowid =
## batch size for a single thread，default 1000
batch_size = 1000
## concurrent running database connections, default 50
max_workers = 50
## true/false，execute or not(default: print the first batched sql and stop running, safe mode)
execute = false

[migrate]
source_db =
source_table =
source_filter =
target_type =
target_host_port =
target_user =
target_password =
target_table =
execute = false

